service: sls-authentication

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  environment: 
    SECRET: ${ssm:/secret}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:eu-west-2:*:table/users"


functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
